# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.provision :shell, :inline => "MACHINE=64 /platform/linux/bootstrap.sh"
  config.vm.synced_folder "../..", "/platform"
  config.vm.network :forwarded_port, host: 8220, guest: 22
end

