# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.provision :shell, :inline => "MACHINE=32 /platform/linux/bootstrap.sh"
  config.vm.synced_folder "../..", "/platform"
  config.vm.network :forwarded_port, host: 8221, guest: 22
end

